### ISSUE TITLE
./ratio_break: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by ./ratio_break)

### ISSUE THREAD

**Issue by masonc15** [ben-carew/ratio_breaks#2]
Hi, 

No worries if you're not maintaining this, but I ran into this error and despite updating glibc a few times, still couldn't get it to work.  I might need to compile and build it again if you wouldn't mind sharing how you did that.  Thanks!

**Comment by masonc15** [comment]
?

**Comment by ben-carew** [comment]
Hi Colin,

Thanks for using my app! The compilation instructions are in the comments at the start of the code.
I should probably put it in the readme file.
I compiled it with g++ ratio_break.cpp -o ratio_break -lncurses
Hopefully that solves your problem, let me know if it's still causing issues (not sure how much I can do to help though).

Cheers,
Ben
